### ISSUE TITLE
Citing this repository

### ISSUE THREAD

**Issue by kevinmatthes** [hungrybluedev/geo#2]
Hello, @hungrybluedev!

Thank you for your very helpful blog entry in the V discussions!  I am working on a V CLI myself, at the moment, and your explanations were an important source of information on how to work with the `flag` module of the standard library.  In order to mention the influence of your work to my software appropriately, I would like to cite this repository in my CITATION.cff.

CITATION.cff is a technology to make software citable by the provision of a configuration file named `CITATION.cff` in its repository root.  Users willing to cite the software can then grab the required metadata -- either from the "Cite this repository" blob GitHub renders on the project's main page to get the data in APA and / or BibTeX formats or with software like [Aeruginous' `cffreference` mode](https://github.com/kevinmatthes/aeruginous-rs) to fetch the data for another CITATION.cff's `references` section.

From the repository structure as well as the publicly available information, I deduced the following data for this repository:

```yaml
abstract: A sample CLI tool made in V that prints geometric shapes to the screen.
authors:
  - alias: hungrybluedev
    family-names: Haldar
    given-names: Subhomoy
cff-version: 1.2.0
date-released: 2023-04-20
license: MIT
message: Please cite this software using these information.
repository-code: https://github.com/hungrybluedev/geo
title: geo
url: https://github.com/hungrybluedev/geo
version: 0.2.4
```

I would like to ask you to tell me whether these information are suitable to cite your work.  If you would like to keep the data in your repository such that other users can cite it easily, as well, I can also submit you a complete basic setup as a PR.
